site_title = "wtq爱看的论文"
limit_days = 30
cache_url = "https://wtqwtq.github.io/wtq_legged_papaer_daily_arxiv/cache.json"

[[sources]]
limit = 150
category = "cs.RO"
title = "机器人技术"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
